export const tasksGo = [
  {
    id: 40001,
    title: "Hello, World!",
    difficulty: "Easy",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию hello(), которая возвращает строку \"Hello, World!\".",
    initialCode: "func hello() string {\n  // Ваш код\n}",
    expectedOutput: "Hello, World!",
    solution: "func hello() string {\n  return \"Hello, World!\"\n}",
  },
  {
    id: 40002,
    title: "Объявление переменных",
    difficulty: "Easy",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "single-choice",
    description: "Какой синтаксис объявления переменной НЕвалиден в Go?",
    options: [
      "var x int = 10",
      "x := 10",
      "var x = 10",
      "int x = 10",
    ],
    correctAnswer: "int x = 10",
    solution: "Go использует постфиксный тип: var x int = 10, или краткую форму x := 10.",
  },
  {
    id: 40003,
    title: "Типы данных",
    difficulty: "Easy",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "multi-choice",
    description: "Выберите все встроенные целочисленные типы в Go:",
    options: [
      "int",
      "int64",
      "uint",
      "Integer",
      "int32",
    ],
    correctAnswer: [0, 1, 2, 4],
    solution: "Go предоставляет int, int8/16/32/64, uint, uint8/16/32/64. Типа Integer не существует.",
  },
  {
    id: 40004,
    title: "Множественный возврат",
    difficulty: "Easy",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "output-predictor",
    description: "Что выведет код?",
    initialCode: `func divide(a, b int) (int, error) {
  if b == 0 {
    return 0, errors.New("division by zero")
  }
  return a / b, nil
}
func main() {
  res, _ := divide(10, 3)
  fmt.Println(res)
}`,
    expectedOutput: "3",
    solution: "Функция divide возвращает (int, error). _ игнорирует ошибку. 10 / 3 = 3 (целочисленное деление).",
  },
  {
    id: 40005,
    title: "Срезы (slices)",
    difficulty: "Easy",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "single-choice",
    description: "Что выведет код?\n\nnums := []int{1, 2, 3, 4, 5}\ns := nums[1:4]\nfmt.Println(s)",
    options: [
      "[1 2 3]",
      "[2 3 4]",
      "[2 3 4 5]",
      "[1 2 3 4]",
    ],
    correctAnswer: "[2 3 4]",
    solution: "Срез nums[1:4] включает элементы с индекса 1 по 3 (не включая 4). Результат: [2 3 4].",
  },
  {
    id: 40006,
    title: "Указатели",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "output-predictor",
    description: "Что выведет код?",
    initialCode: `func main() {
  x := 42
  p := &x
  *p = 21
  fmt.Println(x)
}`,
    expectedOutput: "21",
    solution: "p — указатель на x. Изменение *p меняет и x.",
  },
  {
    id: 40007,
    title: "Структуры и методы",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Создайте структуру Rectangle с полями width, height (float64) и метод area(), возвращающий площадь.",
    initialCode: `type Rectangle struct {
  width  float64
  height float64
}

// Ваш код`,
    expectedOutput: "50",
    solution: "func (r Rectangle) area() float64 {\n  return r.width * r.height\n}",
  },
  {
    id: 40008,
    title: "Интерфейсы",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "single-choice",
    description: "Когда тип удовлетворяет интерфейсу в Go?",
    options: [
      "Когда явно implements интерфейс",
      "Когда реализует все методы интерфейса",
      "Когда наследуется от интерфейса",
      "Только если интерфейс пустой",
    ],
    correctAnswer: "Когда реализует все методы интерфейса",
    solution: "Go использует неявную реализацию интерфейсов: тип автоматически удовлетворяет интерфейсу, если реализует все его методы.",
  },
  {
    id: 40009,
    title: "Горутины",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "single-choice",
    description: "Как запустить функцию f() в отдельной горутине?",
    options: [
      "go f()",
      "thread f()",
      "async f()",
      "goroutine f()",
    ],
    correctAnswer: "go f()",
    solution: "Ключевое слово go перед вызовом функции запускает её в лёгком потоке — горутине.",
  },
  {
    id: 40010,
    title: "Каналы",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "output-predictor",
    description: "Что выведет код?",
    initialCode: `func main() {
  ch := make(chan int)
  go func() { ch <- 42 }()
  fmt.Println(<-ch)
}`,
    expectedOutput: "42",
    solution: "Канал ch передаёт значение 42 из горутины в main. <-ch читает из канала.",
  },
  {
    id: 40011,
    title: "Отложенные вызовы",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "output-predictor",
    description: "Что выведет код?",
    initialCode: `func main() {
  defer fmt.Print("world ")
  fmt.Print("hello ")
}`,
    expectedOutput: "hello world",
    solution: "defer откладывает выполнение до выхода из функции. Выполняется в обратном порядке LIFO.",
  },
  {
    id: 40012,
    title: "Обработка ошибок",
    difficulty: "Medium",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию safeDivide(a, b float64) (float64, error), возвращающую ошибку при b == 0.",
    initialCode: `import "errors"

func safeDivide(a, b float64) (float64, error) {
  // Ваш код
}`,
    expectedOutput: "error",
    solution: "func safeDivide(a, b float64) (float64, error) {\n  if b == 0 {\n    return 0, errors.New(\"division by zero\")\n  }\n  return a / b, nil\n}",
  },
  {
    id: 40013,
    title: "Метод sort.Slice",
    difficulty: "Hard",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Отсортируйте срез чисел по убыванию с помощью sort.Slice.",
    initialCode: `import "sort"

func sortDesc(nums []int) []int {
  // Ваш код
}`,
    expectedOutput: "[5 4 3 1 1]",
    solution: "func sortDesc(nums []int) []int {\n  sort.Slice(nums, func(i, j int) bool {\n    return nums[i] > nums[j]\n  })\n  return nums\n}",
  },
  {
    id: 40014,
    title: "sync.WaitGroup",
    difficulty: "Hard",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Используя sync.WaitGroup, дождитесь завершения 3 горутин, каждая печатает число от 1 до 3.",
    initialCode: `import (
  "fmt"
  "sync"
)

func printNums() {
  var wg sync.WaitGroup
  // Ваш код
}`,
    solution: "func printNums() {\n  var wg sync.WaitGroup\n  for i := 1; i <= 3; i++ {\n    wg.Add(1)\n    go func(n int) {\n      defer wg.Done()\n      fmt.Println(n)\n    }(i)\n  }\n  wg.Wait()\n}",
  },
  {
    id: 40015,
    title: "Паттерн Select",
    difficulty: "Hard",
    topic: "Go Syntax",
    card: "Go Syntax",
    stack: "Go",
    module: "Основы",
    mode: "single-choice",
    description: "Что делает select в Go?",
    options: [
      "Выбирает случайный case из готовых каналов",
      "Выполняет все case последовательно",
      "Создаёт новый канал",
      "Закрывает канал",
    ],
    correctAnswer: "Выбирает случайный case из готовых каналов",
    solution: "select ждёт, пока один из каналов будет готов, и выполняет соответствующий case. При нескольких готовых выбирает случайный.",
  },
  {
    id: 40016,
    title: "Функция с вариативными параметрами",
    difficulty: "Easy",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию sum(nums ...int) int, которая суммирует все переданные числа.",
    initialCode: "func sum(nums ...int) int {\n  // Ваш код\n}",
    solution: "func sum(nums ...int) int {\n  total := 0\n  for _, n := range nums {\n    total += n\n  }\n  return total\n}",
  },
  {
    id: 40017,
    title: "Замыкание (closure)",
    difficulty: "Easy",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию counter() func() int, возвращающую замыкание, которое увеличивает счётчик на 1 при каждом вызове.",
    initialCode: "func counter() func() int {\n  // Ваш код\n}",
    solution: "func counter() func() int {\n  x := 0\n  return func() int {\n    x++\n    return x\n  }\n}",
  },
  {
    id: 40018,
    title: "Работа с картой (map)",
    difficulty: "Easy",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию wordCount(s string) map[string]int, которая подсчитывает количество каждого слова в строке (слова разделены пробелами).",
    initialCode: `import "strings"

func wordCount(s string) map[string]int {
  // Ваш код
}`,
    solution: "func wordCount(s string) map[string]int {\n  m := make(map[string]int)\n  for _, w := range strings.Fields(s) {\n    m[w]++\n  }\n  return m\n}",
  },
  {
    id: 40019,
    title: "Рекурсия: факториал",
    difficulty: "Easy",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите рекурсивную функцию factorial(n int) int, которая вычисляет факториал числа n.",
    initialCode: "func factorial(n int) int {\n  // Ваш код\n}",
    solution: "func factorial(n int) int {\n  if n <= 1 {\n    return 1\n  }\n  return n * factorial(n-1)\n}",
  },
  {
    id: 40020,
    title: "Проверка палиндрома",
    difficulty: "Easy",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию isPalindrome(s string) bool, которая проверяет, является ли строка палиндромом.",
    initialCode: "func isPalindrome(s string) bool {\n  // Ваш код\n}",
    solution: "func isPalindrome(s string) bool {\n  for i := 0; i < len(s)/2; i++ {\n    if s[i] != s[len(s)-1-i] {\n      return false\n    }\n  }\n  return true\n}",
  },
  {
    id: 40021,
    title: "Поиск в срезе",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию findIndex(slice []int, val int) int, возвращающую индекс первого вхождения val в срезе или -1 если не найдено.",
    initialCode: "func findIndex(slice []int, val int) int {\n  // Ваш код\n}",
    solution: "func findIndex(slice []int, val int) int {\n  for i, v := range slice {\n    if v == val {\n      return i\n    }\n  }\n  return -1\n}",
  },
  {
    id: 40022,
    title: "Умножение матриц",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию transpose(matrix [][]int) [][]int, которая транспонирует матрицу (меняет строки и столбцы местами).",
    initialCode: "func transpose(matrix [][]int) [][]int {\n  // Ваш код\n}",
    solution: "func transpose(matrix [][]int) [][]int {\n  rows, cols := len(matrix), len(matrix[0])\n  res := make([][]int, cols)\n  for i := range res {\n    res[i] = make([]int, rows)\n    for j := range res[i] {\n      res[i][j] = matrix[j][i]\n    }\n  }\n  return res\n}",
  },
  {
    id: 40023,
    title: "Интерфейс Stringer",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Создайте тип Person с полями Name (string) и Age (int). Реализуйте метод String() string, возвращающий \"Name: Age years\".",
    initialCode: `type Person struct {
  Name string
  Age  int
}

// Ваш код`,
    solution: "func (p Person) String() string {\n  return fmt.Sprintf(\"%s: %d years\", p.Name, p.Age)\n}",
  },
  {
    id: 40024,
    title: "Тип error из string",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Создайте тип MyError с полем Msg string. Реализуйте метод Error() string.",
    initialCode: `type MyError struct {
  Msg string
}

// Ваш код`,
    solution: "func (e MyError) Error() string {\n  return e.Msg\n}",
  },
  {
    id: 40025,
    title: "Канал с буфером",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию sendData(ch chan<- int, nums []int), которая отправляет числа из nums в канал ch.",
    initialCode: "func sendData(ch chan<- int, nums []int) {\n  // Ваш код\n  close(ch)\n}",
    solution: "func sendData(ch chan<- int, nums []int) {\n  for _, n := range nums {\n    ch <- n\n  }\n  close(ch)\n}",
  },
  {
    id: 40026,
    title: "Чтение из канала",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию sumFromChannel(ch <-chan int) int, которая читает числа из канала пока он открыт и возвращает их сумму.",
    initialCode: "func sumFromChannel(ch <-chan int) int {\n  // Ваш код\n}",
    solution: "func sumFromChannel(ch <-chan int) int {\n  total := 0\n  for n := range ch {\n    total += n\n  }\n  return total\n}",
  },
  {
    id: 40027,
    title: "Mutex-защищённый счётчик",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Создайте тип SafeCounter с мьютексом и методами Increment() и Value() int.",
    initialCode: `import "sync"

type SafeCounter struct {
  mu sync.Mutex
  v  int
}

// Ваш код`,
    solution: "func (c *SafeCounter) Increment() {\n  c.mu.Lock()\n  c.v++\n  c.mu.Unlock()\n}\nfunc (c *SafeCounter) Value() int {\n  c.mu.Lock()\n  defer c.mu.Unlock()\n  return c.v\n}",
  },
  {
    id: 40028,
    title: "Генератор чисел Фибоначчи",
    difficulty: "Medium",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию fib(n int) []int, возвращающую первые n чисел Фибоначчи.",
    initialCode: "func fib(n int) []int {\n  // Ваш код\n}",
    solution: "func fib(n int) []int {\n  if n <= 0 { return []int{} }\n  res := make([]int, n)\n  res[0] = 1\n  if n > 1 { res[1] = 1 }\n  for i := 2; i < n; i++ {\n    res[i] = res[i-1] + res[i-2]\n  }\n  return res\n}",
  },
  {
    id: 40029,
    title: "Удаление дубликатов из среза",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию unique(nums []int) []int, возвращающую срез без дубликатов (сохраняя порядок).",
    initialCode: "func unique(nums []int) []int {\n  // Ваш код\n}",
    solution: "func unique(nums []int) []int {\n  seen := make(map[int]bool)\n  res := []int{}\n  for _, n := range nums {\n    if !seen[n] {\n      seen[n] = true\n      res = append(res, n)\n    }\n  }\n  return res\n}",
  },
  {
    id: 40030,
    title: "Бинарный поиск",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию binarySearch(sorted []int, target int) int, возвращающую индекс target в отсортированном срезе или -1.",
    initialCode: "func binarySearch(sorted []int, target int) int {\n  // Ваш код\n}",
    solution: "func binarySearch(sorted []int, target int) int {\n  l, r := 0, len(sorted)-1\n  for l <= r {\n    mid := (l + r) / 2\n    if sorted[mid] == target { return mid }\n    if sorted[mid] < target { l = mid + 1 } else { r = mid - 1 }\n  }\n  return -1\n}",
  },
  {
    id: 40031,
    title: "Пузырьковая сортировка",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию bubbleSort(nums []int) []int, сортирующую срез пузырьком по возрастанию.",
    initialCode: "func bubbleSort(nums []int) []int {\n  // Ваш код\n}",
    solution: "func bubbleSort(nums []int) []int {\n  n := len(nums)\n  for i := 0; i < n-1; i++ {\n    for j := 0; j < n-i-1; j++ {\n      if nums[j] > nums[j+1] {\n        nums[j], nums[j+1] = nums[j+1], nums[j]\n      }\n    }\n  }\n  return nums\n}",
  },
  {
    id: 40032,
    title: "Слияние отсортированных срезов",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию merge(a, b []int) []int, сливающую два отсортированных среза в один отсортированный.",
    initialCode: "func merge(a, b []int) []int {\n  // Ваш код\n}",
    solution: "func merge(a, b []int) []int {\n  res := make([]int, 0, len(a)+len(b))\n  i, j := 0, 0\n  for i < len(a) && j < len(b) {\n    if a[i] < b[j] {\n      res = append(res, a[i]); i++\n    } else {\n      res = append(res, b[j]); j++\n    }\n  }\n  res = append(res, a[i:]...)\n  res = append(res, b[j:]...)\n  return res\n}",
  },
  {
    id: 40033,
    title: "Параллельная сумма",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию parallelSum(nums []int, workers int) int, которая суммирует числа параллельно через горутины и каналы.",
    initialCode: "func parallelSum(nums []int, workers int) int {\n  // Ваш код\n}",
    solution: "func parallelSum(nums []int, workers int) int {\n  chunk := (len(nums) + workers - 1) / workers\n  ch := make(chan int, workers)\n  for w := 0; w < workers; w++ {\n    go func(start int) {\n      sum := 0\n      end := start + chunk\n      if end > len(nums) { end = len(nums) }\n      for _, n := range nums[start:end] { sum += n }\n      ch <- sum\n    }(w * chunk)\n  }\n  total := 0\n  for w := 0; w < workers; w++ {\n    total += <-ch\n  }\n  return total\n}",
  },
  {
    id: 40034,
    title: "Публикация-подписка (fan-out)",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию fanOut(in <-chan int, n int) []<-chan int, которая распределяет данные из in по n каналам.",
    initialCode: "func fanOut(in <-chan int, n int) []<-chan int {\n  // Ваш код\n}",
    solution: "func fanOut(in <-chan int, n int) []<-chan int {\n  outs := make([]chan int, n)\n  for i := range outs { outs[i] = make(chan int) }\n  go func() {\n    idx := 0\n    for v := range in {\n      outs[idx] <- v\n      idx = (idx + 1) % n\n    }\n    for _, ch := range outs { close(ch) }\n  }()\n  res := make([]<-chan int, n)\n  for i := range res { res[i] = outs[i] }\n  return res\n}",
  },
  {
    id: 40035,
    title: "graceful shutdown",
    difficulty: "Hard",
    topic: "Go: Структуры данных",
    card: "Go: Структуры данных",
    stack: "Go",
    module: "Основы",
    mode: "code",
    description: "Напишите функцию worker(id int, jobs <-chan int, done chan<- bool), которая читает jobs и посылает true в done после закрытия канала.",
    initialCode: "func worker(id int, jobs <-chan int, done chan<- bool) {\n  // Ваш код\n}",
    solution: "func worker(id int, jobs <-chan int, done chan<- bool) {\n  for range jobs {\n    // processing\n  }\n  done <- true\n}",
  },
];
