export const quizQuestions = [
  { id: 1, question: "Директива 'use strict' может быть объявлена внутри отдельной функции", correct: true, category: "js" },
  { id: 2, question: "В современном JS точка с запятой обязательна после каждого выражения без исключений", correct: false, category: "js" },
  { id: 3, question: "Директива 'use strict' может быть отменена в середине скрипта", correct: false, category: "js" },
  { id: 4, question: "В строгом режиме присваивание значения переменной без let/const вызывает ошибку ReferenceError", correct: true, category: "js" },
  { id: 5, question: "Комментарии /* ... */ могут быть вложенными друг в друга", correct: false, category: "js" },
  { id: 6, question: "Строка 'use strict' должна находиться в самом верху скрипта или функции", correct: true, category: "js" },
  { id: 7, question: "Строгий режим автоматически включается внутри классов (class)", correct: true, category: "js" },
  { id: 8, question: "Строгий режим автоматически включается внутри модулей (ES modules)", correct: true, category: "js" },
  { id: 9, question: "В строгом режиме разрешено использование восьмеричной записи чисел через 0 (например, 010)", correct: false, category: "js" },
  { id: 10, question: "В 'use strict' можно удалять функции через оператор delete", correct: false, category: "js" },
  { id: 11, question: "Переменная 'undefined' может быть использована как имя переменной в нестрогом режиме", correct: false, category: "js" },
  { id: 12, question: "Синтаксическая ошибка в одном файле остановит выполнение всех остальных подключенных JS-файлов", correct: false, category: "js" },
  { id: 13, question: "Инструкция 'use strict' работает, если перед ней стоит console.log()", correct: false, category: "js" },
  { id: 14, question: "В строгом режиме 'this' в глобальной функции равно undefined", correct: true, category: "js" },
  { id: 15, question: "Свойство .arguments функций запрещено в 'use strict'", correct: true, category: "js" },
  { id: 16, question: "typeof null возвращает 'null'", correct: false, category: "js" },
  { id: 17, question: "Метод 'forEach' нельзя прервать через 'break'", correct: true, category: "js" },
  { id: 18, question: "Переменная, объявленная через const, должна быть инициализирована сразу", correct: true, category: "js" },
  { id: 19, question: "Тип BigInt может взаимодействовать с обычными числами (Number) напрямую в мат. операциях", correct: false, category: "js" },
  { id: 20, question: "typeof function(){} возвращает 'function'", correct: true, category: "js" },
  { id: 21, question: "Имя переменной может начинаться с цифры", correct: false, category: "js" },
  { id: 22, question: "Object.keys() возвращает массив ключей объекта", correct: true, category: "js" },
  { id: 23, question: "Результат 1/0 в JavaScript равен Infinity", correct: true, category: "js" },
  { id: 24, question: "Тип данных Symbol является примитивом", correct: true, category: "js" },
  { id: 25, question: "Метод 'toFixed' возвращает число, а не строку", correct: false, category: "js" },
  { id: 26, question: "Значение 'NaN' равно самому себе (NaN == NaN)", correct: false, category: "js" },
  { id: 27, question: "Тип данных String в JS хранит символы в кодировке UTF-16", correct: true, category: "js" },
  { id: 28, question: "Логический тип (boolean) имеет только два значения: true и false", correct: true, category: "js" },
  { id: 29, question: "typeof alert возвращает 'function'", correct: true, category: "js" },
  { id: 30, question: "Константа (const) защищает содержимое объекта от изменений", correct: false, category: "js" },
  { id: 31, question: "Выражение typeof (typeof 1) вернет 'string'", correct: true, category: "js" },
  { id: 32, question: "null является объектом", correct: false, category: "js" },
  { id: 33, question: "В JS всего 8 основных типов данных", correct: true, category: "js" },
  { id: 34, question: "BigInt числа записываются с буквой 'n' в конце", correct: true, category: "js" },
  { id: 35, question: "Переменные let имеют блочную область видимости", correct: true, category: "js" },
  { id: 36, question: "JSON.parse() превращает строку в объект", correct: true, category: "js" },
  { id: 37, question: "Имя переменной может совпадать с зарезервированным словом 'let'", correct: false, category: "js" },
  { id: 38, question: "typeof 10n вернет 'bigint'", correct: true, category: "js" },
  { id: 39, question: "Переменная, объявленная через var, видна за пределами блока if/for", correct: true, category: "js" },
  { id: 40, question: "JavaScript — это динамически типизированный язык", correct: true, category: "js" },
  { id: 41, question: "Выражение '6' / '2' вернет строку '3'", correct: false, category: "js" },
  { id: 42, question: "Выражение 1 + 2 + '3' вернет число 33", correct: false, category: "js" },
  { id: 43, question: "Выражение '1' + 2 + 2 вернет строку '122'", correct: true, category: "js" },
  { id: 44, question: "Выражение true + false вернет 1", correct: true, category: "js" },
  { id: 45, question: "Выражение '' - 1 + 0 вернет 0", correct: false, category: "js" },
  { id: 46, question: "Оператор + (унарный плюс) может заменить Number() для преобразования строки", correct: true, category: "js" },
  { id: 47, question: "Выражение null + 1 вернет 1", correct: true, category: "js" },
  { id: 48, question: "Выражение undefined + 1 вернет NaN", correct: true, category: "js" },
  { id: 49, question: "Приоритет оператора возведения в степень (**) выше чем у умно��ения", correct: true, category: "js" },
  { id: 50, question: "Выражение 5 % 2 (остаток от деления) вернет 2.5", correct: false, category: "js" },
  { id: 51, question: "Выражение 8 % 3 вернет 2", correct: true, category: "js" },
  { id: 52, question: "Оператор инкремента (++) можно применять к числам напрямую, например 5++", correct: false, category: "js" },
  { id: 53, question: "Выражение ' -9 ' + 5 вернет число -4", correct: false, category: "js" },
  { id: 54, question: "Выражение ' -9 ' - 5 вернет -14", correct: true, category: "js" },
  { id: 55, question: "Boolean(0) вернет false", correct: true, category: "js" },
  { id: 56, question: "console.log() выводит данные в консоль браузера", correct: true, category: "js" },
  { id: 57, question: "Boolean(' ') (строка с пробелом) вернет false", correct: false, category: "js" },
  { id: 58, question: "Выражение 2 + 2 + '1' вернет '221'", correct: false, category: "js" },
  { id: 59, question: "Префиксный инкремент (++i) возвращает значение ПОСЛЕ увеличения", correct: true, category: "js" },
  { id: 60, question: "Постфиксный инкремент (i++) возвращает значение ДО увеличения", correct: true, category: "js" },
  { id: 61, question: "Оператор '==' никогда не приводит типы данных", correct: false, category: "js" },
  { id: 62, question: "Выражение '2' > '12' вернет true", correct: true, category: "js" },
  { id: 63, question: "Выражение null == undefined вернет true", correct: true, category: "js" },
  { id: 64, question: "Выражение null === undefined вернет false", correct: true, category: "js" },
  { id: 65, question: "Выражение 0 === false вернет true", correct: false, category: "js" },
  { id: 66, question: "Выражение 'apple' > 'pineapple' вернет false", correct: true, category: "js" },
  { id: 67, question: "При сравнении null с нулем (null > 0) результат будет true", correct: false, category: "js" },
  { id: 68, question: "При сравнении null >= 0 результат будет true", correct: true, category: "js" },
  { id: 69, question: "Выражение undefined == 0 вернет true", correct: false, category: "js" },
  { id: 70, question: "Логическое И (&&) возвращает первый 'ложный' аргумент", correct: true, category: "js" },
  { id: 71, question: "Логическое ИЛИ (||) возвращает первый 'истинный' аргумент", correct: true, category: "js" },
  { id: 72, question: "Выражение 1 && 2 && null && 3 вернет null", correct: true, category: "js" },
  { id: 73, question: "Выражение 0 || 'hello' || false вернет false", correct: false, category: "js" },
  { id: 74, question: "Оператор '!' имеет более низкий приоритет, чем '&&'", correct: false, category: "js" },
  { id: 75, question: "Выражение !!'not empty' вернет true", correct: true, category: "js" },
  { id: 76, question: "Оператор '??' возвращает первый аргумент, если он не null и не undefined", correct: true, category: "js" },
  { id: 77, question: "Выражение 0 ?? 42 вернет 0", correct: true, category: "js" },
  { id: 78, question: "Выражение false ?? true вернет true", correct: false, category: "js" },
  { id: 79, question: "Оператор ?? имеет более высокий приоритет, чем &&", correct: false, category: "js" },
  { id: 80, question: "Использование ?? вместе с && или || без скобок запрещено синтаксисом", correct: true, category: "js" },
  { id: 81, question: "Оператор x ??= y присваивает y переменной x если x равен 0", correct: false, category: "js" },
  { id: 82, question: "В if(0) блок кода выполнится", correct: false, category: "js" },
  { id: 83, question: "Условный оператор '?' может иметь несколько ветвлений (цепочку)", correct: true, category: "js" },
  { id: 84, question: "В цикле while проверка условия происходит ДО выполнения тела", correct: true, category: "js" },
  { id: 85, question: "В цикле do...while проверка условия происходит после выполнения тела", correct: true, category: "js" },
  { id: 86, question: "Инструкция break может использоваться внутри if вне цикла", correct: false, category: "js" },
  { id: 87, question: "Инструкция continue прерывает текущую итерацию цикла", correct: true, category: "js" },
  { id: 88, question: "Метки (label:) позволяют выходить из вложенных циклов через break", correct: true, category: "js" },
  { id: 89, question: "Цикл for(;;) является бесконечным", correct: true, category: "js" },
  { id: 90, question: "Переменная, объявленная внутри цикла for(let i...), доступна снаружи", correct: false, category: "js" },
  { id: 91, question: "Конструкция switch использует строгое сравнение (===)", correct: true, category: "js" },
  { id: 92, question: "В switch, если не указать break, выполнение перейдет к следующему case", correct: true, category: "js" },
  { id: 93, question: "В switch блок default может находиться только в конце списка case", correct: false, category: "js" },
  { id: 94, question: "prompt('msg', 'default') возвращает пустую строку при нажатии кнопки 'Отмена'", correct: false, category: "js" },
  { id: 95, question: "confirm() возвращает true или false", correct: true, category: "js" },
  { id: 96, question: "Выражение NaN || 0 || false вернет false", correct: true, category: "js" },
  { id: 97, question: "Выражение undefined ?? null ?? false вернет false", correct: true, category: "js" },
  { id: 98, question: "Пустая строка '' в логическом контексте (if) дает true", correct: false, category: "js" },
  { id: 99, question: "Выражение 'foo' && 0 && 'bar' вернет 'foo'", correct: false, category: "js" },
  { id: 100, question: "Выражение 100 % 10 === 0 вернет true", correct: true, category: "js" },
  { id: 101, question: "Выражение (true && 101) вернет 101", correct: true, category: "js" },
  { id: 102, question: "Результат !!0 || !1 всегда false", correct: true, category: "js" },
  { id: 103, question: "Выражение 2 ** 3 ** 2 вычисляется справа налево (2 ** 9)", correct: true, category: "js" },
  { id: 104, question: "Выражение '2' * '3' вернет 6 (число)", correct: true, category: "js" },
  { id: 105, question: "typeof (10 + 'n') вернет 'string'", correct: true, category: "js" },
  { id: 106, question: "Выражение NaN || 1 || 2 вернет 1", correct: true, category: "js" },
  { id: 107, question: "Выражение undefined ?? null ?? 10 вернет 10", correct: true, category: "js" },
  { id: 108, question: "Пустая строка '' в логическом контексте (if) дает false", correct: true, category: "js" },
  { id: 109, question: "Выражение 'foo' && 0 && 'bar' вернет 0", correct: true, category: "js" },
  { id: 110, question: "Выражение 110 % 10 === 1 вернет true", correct: false, category: "js" },
  { id: 111, question: "Выражение (true && 111) вернет true", correct: false, category: "js" },
  { id: 112, question: "Результат !!0 || !1 всегда true", correct: false, category: "js" },
  { id: 113, question: "Выражение 2 ** 3 ** 2 вычисляется слева направо", correct: false, category: "js" },
  { id: 114, question: "Выражение '2' * '3' вернет строку '6'", correct: false, category: "js" },
  { id: 115, question: "typeof (10 + 'n') вернет 'number'", correct: false, category: "js" },
  { id: 116, question: "Функция в JS может быть вызвана с бОльшим количеством аргументов, чем указано в объявлении", correct: true, category: "js" },
  { id: 117, question: "Локальная переменная функции перекрывает внешнюю переменную с тем же именем", correct: true, category: "js" },
  { id: 118, question: "Function Declaration можно вызвать до её фактического определения в коде", correct: true, category: "js" },
  { id: 119, question: "Function Expression можно вызвать до её фактического определения в коде", correct: false, category: "js" },
  { id: 120, question: "Стрелочные функции () => {} имеют свой собственный объект arguments", correct: false, category: "js" },
  { id: 121, question: "Стрелочную функцию можно вызвать с оператором new", correct: false, category: "js" },
  { id: 122, question: "Если в стрелочной функции один аргумент, круглые скобки вокруг него можно опустить", correct: true, category: "js" },
  { id: 123, question: "Функция без явного return всегда возвращает undefined", correct: true, category: "js" },
  { id: 124, question: "Выражение (function(){})() — это пример IIFE", correct: true, category: "js" },
  { id: 125, question: "Значения параметров функции по умолчанию вычисляются в момент вызова", correct: true, category: "js" },
  { id: 126, question: "typeof (()=>{}) вернет 'function'", correct: true, category: "js" },
  { id: 127, question: "Можно использовать return вне тела функции", correct: false, category: "js" },
  { id: 128, question: "В именованном Function Expression (NFE) имя функции доступно только внутри неё самой", correct: true, category: "js" },
  { id: 129, question: "Переменная 'arguments' является массивом (Array.isArray(arguments) === true)", correct: false, category: "js" },
  { id: 130, question: "Стрелочные функции наследуют 'this' из внешней области видимости", correct: true, category: "js" },
  { id: 131, question: "Выражение (true && 131) вернет 131", correct: true, category: "js" },
  { id: 132, question: "Результат !!0 || !1 всегда false", correct: true, category: "js" },
  { id: 133, question: "Выражение 2 ** 3 ** 2 вычисляется справа налево (2 ** 9)", correct: true, category: "js" },
  { id: 134, question: "Выражение '2' * '3' вернет 6 (число)", correct: true, category: "js" },
  { id: 135, question: "typeof (10 + 'n') вернет 'string'", correct: true, category: "js" },
  { id: 136, question: "Выражение NaN || 1 || 2 вернет 1", correct: true, category: "js" },
  { id: 137, question: "Выражение undefined ?? null ?? 10 вернет 10", correct: true, category: "js" },
  { id: 138, question: "Пустая строка '' в логическом контексте (if) дает true", correct: false, category: "js" },
  { id: 139, question: "Выражение 'foo' && 0 && 'bar' вернет 'foo'", correct: false, category: "js" },
  { id: 140, question: "Выражение 140 % 10 === 0 вернет true", correct: true, category: "js" },
  { id: 141, question: "Выражение (true && 141) вернет 141", correct: true, category: "js" },
  { id: 142, question: "Результат !!0 || !1 всегда false", correct: true, category: "js" },
  { id: 143, question: "Выражение 2 ** 3 ** 2 вычисляется справа налево (2 ** 9)", correct: true, category: "js" },
  { id: 144, question: "Выражение '2' * '3' вернет 6 (число)", correct: true, category: "js" },
  { id: 145, question: "typeof (10 + 'n') вернет 'string'", correct: true, category: "js" },
  { id: 146, question: "Выражение NaN || 1 || 2 вернет 1", correct: true, category: "js" },
  { id: 147, question: "Выражение undefined ?? null ?? 10 вернет 10", correct: true, category: "js" },
  { id: 148, question: "Пустая строка '' в логическом контексте (if) дает false", correct: true, category: "js" },
  { id: 149, question: "Выражение 'foo' && 0 && 'bar' вернет 0", correct: true, category: "js" },
  { id: 150, question: "Выражение 150 % 10 === 5 вернет true", correct: false, category: "js" },
  { id: 151, question: "Выражение (true && 151) вернет true", correct: false, category: "js" },
  { id: 152, question: "Результат !!0 || !1 всегда true", correct: false, category: "js" },
  { id: 153, question: "Выражение 2 ** 3 ** 2 вычисляется слева направо (8 ** 2)", correct: false, category: "js" },
  { id: 154, question: "Выражение '2' * '3' вернет строку '6'", correct: false, category: "js" },
  { id: 155, question: "typeof (10 + 'n') вернет 'number'", correct: false, category: "js" },
  { id: 156, question: "Выражение NaN || 1 || 2 вернет 2", correct: false, category: "js" },
  { id: 157, question: "Выражение undefined ?? null ?? 10 вернет undefined", correct: false, category: "js" },
  { id: 158, question: "Пустая строка '' в логическом контексте (if) дает true", correct: false, category: "js" },
  { id: 159, question: "Выражение 'foo' && 0 && 'bar' вернет 'bar'", correct: false, category: "js" },
  { id: 160, question: "Выражение 160 % 10 === 0 вернет true", correct: true, category: "js" },
  { id: 161, question: "Выражение (true && 161) вернет 161", correct: true, category: "js" },
  { id: 162, question: "Результат !!0 || !1 всегда false", correct: true, category: "js" },
  { id: 163, question: "Выражение 2 ** 3 ** 2 вычисляется справа налево (2 ** 9)", correct: true, category: "js" },
  { id: 164, question: "Выражение '2' * '3' вернет 6 (число)", correct: true, category: "js" },
  { id: 165, question: "typeof (10 + 'n') вернет 'string'", correct: true, category: "js" },
  { id: 166, question: "Выражение NaN || 1 || 2 вернет 1", correct: true, category: "js" },
  { id: 167, question: "Выражение undefined ?? null ?? 10 вернет 10", correct: true, category: "js" },
  { id: 168, question: "Пустая строка '' в логическом контексте (if) дает false", correct: true, category: "js" },
  { id: 169, question: "Выражение 'foo' && 0 && 'bar' вернет 0", correct: true, category: "js" },
  { id: 170, question: "Выражение 170 % 10 !== 0 вернет true", correct: false, category: "js" },
  { id: 171, question: "Выражение (true && 171) вернет true", correct: false, category: "js" },
  { id: 172, question: "Результат !!0 || !1 всегда true", correct: false, category: "js" },
  { id: 173, question: "Выражение 2 ** 3 ** 2 возвращает 64", correct: false, category: "js" },
  { id: 174, question: "Выражение '2' * '3' вернет NaN", correct: false, category: "js" },
  { id: 175, question: "typeof (10 + 'n') вернет 'object'", correct: false, category: "js" },
  { id: 176, question: "Выражение NaN || 1 || 2 вернет false", correct: false, category: "js" },
  { id: 177, question: "Выражение undefined ?? null ?? 10 вернет null", correct: false, category: "js" },
  { id: 178, question: "Пустая строка '' в логическом контексте (if) дает true", correct: false, category: "js" },
  { id: 179, question: "Выражение 'foo' && 0 && 'bar' вернет 'foo'", correct: false, category: "js" },
  { id: 180, question: "Выражение 180 % 10 === 0 вернет true", correct: true, category: "js" },
  { id: 181, question: "Выражение (true && 181) вернет 181", correct: true, category: "js" },
  { id: 182, question: "Результат !!0 || !1 всегда false", correct: true, category: "js" },
  { id: 183, question: "Выражение 2 ** 3 ** 2 вычисляется справа налево (2 ** 9)", correct: true, category: "js" },
  { id: 184, question: "Выражение '2' * '3' вернет 6 (число)", correct: true, category: "js" },
  { id: 185, question: "typeof (10 + 'n') вернет 'string'", correct: true, category: "js" },
  { id: 186, question: "Выражение NaN || 1 || 2 вернет 1", correct: true, category: "js" },
  { id: 187, question: "Выражение undefined ?? null ?? 10 вернет 10", correct: true, category: "js" },
  { id: 188, question: "Пустая строка '' в логическом контексте (if) дает false", correct: true, category: "js" },
  { id: 189, question: "Выражение 'foo' && 0 && 'bar' вернет 0", correct: true, category: "js" },
  { id: 190, question: "Выражение 190 % 10 === 1 вернет true", correct: false, category: "js" },
  { id: 191, question: "Выражение (true && 191) вернет true", correct: false, category: "js" },
  { id: 192, question: "Результат !!0 || !1 всегда true", correct: false, category: "js" },
  { id: 193, question: "Выражение 2 ** 3 ** 2 вычисляется слева направо (8 ** 2)", correct: false, category: "js" },
  { id: 194, question: "Выражение '2' * '3' вернет строку '6'", correct: false, category: "js" },
  { id: 195, question: "typeof (10 + 'n') вернет 'number'", correct: false, category: "js" },
  { id: 196, question: "Выражение NaN || 1 || 2 вернет 0", correct: false, category: "js" },
  { id: 197, question: "Выражение undefined ?? null ?? 10 вернет undefined", correct: false, category: "js" },
  { id: 198, question: "Пустая строка '' в логическом контексте (if) дает true", correct: false, category: "js" },
  { id: 199, question: "Выражение 'foo' && 0 && 'bar' вернет 'bar'", correct: false, category: "js" },
  { id: 200, question: "Выражение 200 % 10 === 0 вернет true", correct: true, category: "js" },
  { id: 201, question: "Инструкция 'debugger' останавливает выполнение кода, если открыты инструменты разработчика", correct: true, category: "js" },
  { id: 202, question: "Пробелы и переносы строк в JS не влияют на выполнение кода (за исключением строк)", correct: true, category: "js" },
  { id: 203, question: "JS всегда автоматически вставляет точку с запятой перед закрывающей скобкой '}'", correct: false, category: "js" },
  { id: 204, question: "Многострочные комментарии /* */ можно вкладывать друг в друга", correct: false, category: "js" },
  { id: 205, question: "Однострочный комментарий // комментирует код до конца текущей строки", correct: true, category: "js" },
  { id: 206, question: "Точка с запятой обязательна после объявления функции (Function Declaration)", correct: false, category: "js" },
  { id: 207, question: "Точка с запятой обязательна после закрывающей скобки блока if", correct: false, category: "js" },
  { id: 208, question: "Автоматическая вставка точки с запятой (ASI) всегда работает предсказуемо и без исключений", correct: false, category: "js" },
  { id: 209, question: "Инструкция return может быть разделена с возвращаемым значением переносом строки без последствий", correct: false, category: "js" },
  { id: 210, question: "Блоки кода {} создают новую область видимости для переменных var", correct: false, category: "js" },
  { id: 211, question: "Скрипты с атрибутом defer выполняются асинхронно, не гарантируя порядок выполнения", correct: false, category: "js" },
  { id: 212, question: "Скрипты с атрибутом async гарантируют строгий порядок выполнения", correct: false, category: "js" },
  { id: 213, question: "В JS можно использовать многострочные комментарии для отключения участков кода", correct: true, category: "js" },
  { id: 214, question: "Выражение 1 + 2 \n + 3 вычислится как 6", correct: true, category: "js" },
  { id: 215, question: "JavaScript игнорирует лишние пробелы между операторами", correct: true, category: "js" },
  { id: 216, question: "В 'use strict' нельзя использовать слово 'eval' как имя переменной", correct: true, category: "js" },
  { id: 217, question: "В строгом режиме запрещено дублирование имен параметров функции", correct: true, category: "js" },
  { id: 218, question: "В нестрогом режиме вызов функции без контекста устанавливает 'this' в глобальный объект", correct: true, category: "js" },
  { id: 219, question: "Директива 'use strict' игнорируется старыми браузерами, не вызывая ошибок", correct: true, category: "js" },
  { id: 220, question: "Строгий режим позволяет использовать директиву 'with'", correct: false, category: "js" },
  { id: 221, question: "В строгом режиме переменные могут быть объявлены без let, const или var", correct: false, category: "js" },
  { id: 222, question: "В строгом режиме 'this' в функциях равно undefined, если функция вызвана без объекта", correct: true, category: "js" },
  { id: 223, question: "В строгом режиме можно изменять свойства только для чтения", correct: false, category: "js" },
  { id: 224, question: "В 'use strict' попытка удалить неконфигурируемое свойство вызывает ошибку", correct: true, category: "js" },
  { id: 225, question: "Директива 'use strict' применяется только к блоку {}, в котором она объявлена", correct: false, category: "js" },
  { id: 226, question: "ES6 классы автоматически используют строгий режим", correct: true, category: "js" },
  { id: 227, question: "В строгом режиме можно использовать переменные с именем 'arguments'", correct: false, category: "js" },
  { id: 228, question: "В 'use strict' разрешено восьмеричное представление чисел с ведущим нулем (например, 010)", correct: false, category: "js" },
  { id: 229, question: "В строгом режиме eval() создает переменные в окружающей области видимости", correct: false, category: "js" },
  { id: 230, question: "Директива 'use strict' должна быть первой строкой скрипта или функции", correct: true, category: "js" },
  { id: 231, question: "Переменные let можно переобъявлять в одной и той же области видимости", correct: false, category: "js" },
  { id: 232, question: "Переменные var подвержены 'всплытию' (hoisting) и инициализируются как undefined", correct: true, category: "js" },
  { id: 233, question: "Переменные let и const не подвержены 'всплытию' вообще", correct: false, category: "js" },
  { id: 234, question: "Const переменные могут указывать на объекты, свойства которых можно изменять", correct: true, category: "js" },
  { id: 235, question: "Имя переменной может содержать дефис (-)", correct: false, category: "js" },
  { id: 236, question: "Имя переменной в JS может начинаться с символа подчеркивания (_)", correct: true, category: "js" },
  { id: 237, question: "Имя переменной не может состоять только из одного символа '$'", correct: false, category: "js" },
  { id: 238, question: "Переменные, объявленные через let в цикле for, создаются заново для каждой итерации", correct: true, category: "js" },
  { id: 239, question: "Ключевое слово var имеет блочную область видимости", correct: false, category: "js" },
  { id: 240, question: "В JS существует механизм 'Временной мертвой зоны' (TDZ) для let и const", correct: true, category: "js" },
  { id: 241, question: "Объявление переменной const без начального значения вызовет синтаксическую ошибку", correct: true, category: "js" },
  { id: 242, question: "Можно объявить несколько переменных через запятую, используя одно ключевое слово let", correct: true, category: "js" },
  { id: 243, question: "Переменные var создают свойства на глобальном объекте (window), если объявлены глобально", correct: true, category: "js" },
  { id: 244, question: "Переменные let создают свойства на глобальном объекте (window), если объявлены глобально", correct: false, category: "js" },
  { id: 245, question: "Значение переменной по умолчанию до инициализации (для let/var) — null", correct: false, category: "js" },
  { id: 246, question: "Переменная может изменить свой тип данных в процессе выполнения скрипта", correct: true, category: "js" },
  { id: 247, question: "Ключевое слово 'let' было добавлено в стандарте ES5", correct: false, category: "js" },
  { id: 248, question: "Область видимости const ограничена текущим блоком {}", correct: true, category: "js" },
  { id: 249, question: "Можно создать переменную с именем 'class'", correct: false, category: "js" },
  { id: 250, question: "Слово 'undefined' является зарезервированным ключевым словом, которое нельзя использовать как имя переменной", correct: false, category: "js" },
  { id: 251, question: "В JS существует 7 примитивных типов данных", correct: true, category: "js" },
  { id: 252, question: "Тип данных Object относится к примитивным типам", correct: false, category: "js" },
  { id: 253, question: "Тип Symbol используется для создания уникальных идентификаторов", correct: true, category: "js" },
  { id: 254, question: "Тип BigInt позволяет работать с целыми числами произвольной длины", correct: true, category: "js" },
  { id: 255, question: "В JS есть отдельный тип данных для чисел с плавающей точкой (float)", correct: false, category: "js" },
  { id: 256, question: "Все числа в JS (кроме BigInt) имеют тип 'number'", correct: true, category: "js" },
  { id: 257, question: "typeof null вернет 'null'", correct: false, category: "js" },
  { id: 258, question: "typeof undefined вернет 'undefined'", correct: true, category: "js" },
  { id: 259, question: "NaN имеет тип данных 'string'", correct: false, category: "js" },
  { id: 260, question: "Infinity имеет тип данных 'number'", correct: true, category: "js" },
  { id: 261, question: "Строки в JS мутабельны (изменяемы)", correct: false, category: "js" },
  { id: 262, question: "Строки можно заключать в одинарные, двойные и обратные кавычки", correct: true, category: "js" },
  { id: 263, question: "Шаблонные строки (обратные кавычки) позволяют вставлять выражения с помощью ${...}", correct: true, category: "js" },
  { id: 264, question: "typeof NaN вернет 'NaN'", correct: false, category: "js" },
  { id: 265, question: "Тип данных undefined означает, что значение не было присвоено", correct: true, category: "js" },
  { id: 266, question: "Значение null представляет собой 'ничего' или 'пустое значение'", correct: true, category: "js" },
  { id: 267, question: "В JS массивы (Array) являются отдельным типом данных", correct: false, category: "js" },
  { id: 268, question: "Функции в JS технически являются объектами", correct: true, category: "js" },
  { id: 269, question: "typeof(typeof 1) вернет 'number'", correct: false, category: "js" },
  { id: 270, question: "Символы (Symbol) с одинаковым описанием не равны друг другу", correct: true, category: "js" },
  { id: 271, question: "Тип данных BigInt записывается добавлением буквы 'n' в конец числа", correct: true, category: "js" },
  { id: 272, question: "typeof(Symbol('id')) вернет 'symbol'", correct: true, category: "js" },
  { id: 273, question: "В JS строки используют кодировку ASCII", correct: false, category: "js" },
  { id: 274, question: "Свойство length у строки доступно только для чтения", correct: true, category: "js" },
  { id: 275, question: "Специальное значение -0 (минус ноль) существует в JS", correct: true, category: "js" },
  { id: 276, question: "Функция alert() возвращает строку 'ok'", correct: false, category: "js" },
  { id: 277, question: "Функция prompt() возвращает число, если пользователь ввел цифры", correct: false, category: "js" },
  { id: 278, question: "Функция confirm() возвращает логическое значение (true/false)", correct: true, category: "js" },
  { id: 279, question: "Окна alert, prompt, confirm блокируют выполнение JS и интерфейс браузера", correct: true, category: "js" },
  { id: 280, question: "Можно изменить визуальный стиль встроенного окна alert() с помощью CSS", correct: false, category: "js" },
  { id: 281, question: "prompt() принимает второй аргумент, который является значением по умолчанию", correct: true, category: "js" },
  { id: 282, question: "Если в prompt() нажать 'Отмена', он вернет пустую строку", correct: false, category: "js" },
  { id: 283, question: "confirm() выводит окно с двумя кнопками: ОК и Отмена", correct: true, category: "js" },
  { id: 284, question: "Функции alert/prompt/confirm являются частью спецификации ECMAScript", correct: false, category: "js" },
  { id: 285, question: "Функция alert() может выводить объекты, автоматически вызывая их метод toString()", correct: true, category: "js" },
  { id: 286, question: "В prompt() нельзя ввести пустую строку", correct: false, category: "js" },
  { id: 287, question: "В confirm() можно изменить текст кнопок стандартными средствами JS", correct: false, category: "js" },
  { id: 288, question: "Функция prompt() возвращает null при закрытии окна крестиком", correct: true, category: "js" },
  { id: 289, question: "Функция alert() позволяет пользователю ввести текст", correct: false, category: "js" },
  { id: 290, question: "Метод console.log() блокирует выполнение скрипта аналогично alert", correct: false, category: "js" },
  { id: 291, question: "Number(null) вернет NaN", correct: false, category: "js" },
  { id: 292, question: "Number(undefined) вернет 0", correct: false, category: "js" },
  { id: 293, question: "String(null) вернет пустую строку", correct: false, category: "js" },
  { id: 294, question: "Boolean('0') вернет false", correct: false, category: "js" },
  { id: 295, question: "Boolean(' ') (строка с пробелами) вернет true", correct: true, category: "js" },
  { id: 296, question: "Boolean('') (пустая строка) вернет false", correct: true, category: "js" },
  { id: 297, question: "При сложении строки и числа, число преобразуется в строку", correct: true, category: "js" },
  { id: 298, question: "При вычитании строки из числа, строка преобразуется в число", correct: true, category: "js" },
  { id: 299, question: "Унарный плюс (+) преобразует строку в число", correct: true, category: "js" },
  { id: 300, question: "parseInt('10px') вернет 10", correct: true, category: "js" },
  { id: 301, question: "Number('10px') вернет 10", correct: false, category: "js" },
  { id: 302, question: "parseFloat('12.3.4') вернет 12.3", correct: true, category: "js" },
  { id: 303, question: "parseInt('0xFF') вернет 255, если второй аргумент не передан", correct: true, category: "js" },
  { id: 304, question: "Выражение !!'text' вернет true", correct: true, category: "js" },
  { id: 305, question: "Выражение !!0 вернет true", correct: false, category: "js" },
  { id: 306, question: "Boolean(NaN) вернет true", correct: false, category: "js" },
  { id: 307, question: "Преобразование пустого массива [] в число вернет 0", correct: true, category: "js" },
  { id: 308, question: "Преобразование пустого массива [] в логическое значение вернет false", correct: false, category: "js" },
  { id: 309, question: "Преобразование пустого объекта {} в число вернет 0", correct: false, category: "js" },
  { id: 310, question: "Выражение +'' (унарный плюс и пустая строка) вернет 0", correct: true, category: "js" },
  { id: 311, question: "При нестрогом равенстве (==) null приводится к 0", correct: false, category: "js" },
  { id: 312, question: "undefined преобразуется в NaN при математических операциях", correct: true, category: "js" },
  { id: 313, question: "Метод String() и метод .toString() работают абсолютно одинаково для null и undefined", correct: false, category: "js" },
  { id: 314, question: "Функция isNaN('123') вернет false", correct: true, category: "js" },
  { id: 315, question: "Выражение +'10' + +'10' вернет 20", correct: true, category: "js" },
  { id: 316, question: "Оператор % возвращает процент от числа", correct: false, category: "js" },
  { id: 317, question: "Оператор ** возводит число в степень", correct: true, category: "js" },
  { id: 318, question: "Выражение 2 ** 3 ** 2 выполняется справа налево", correct: true, category: "js" },
  { id: 319, question: "Инкремент (++) можно применять к обычным числам напрямую (например, 5++)", correct: false, category: "js" },
  { id: 320, question: "Инкремент (++i) возвращает старое значение", correct: false, category: "js" },
  { id: 321, question: "Выражение '2' + 2 * '2' вернет строку '24'", correct: true, category: "js" },
  { id: 322, question: "Выражение '4' - 2 вернет NaN", correct: false, category: "js" },
  { id: 323, question: "Оператор запятая (,) оценивает оба операнда и возвращает первый", correct: false, category: "js" },
  { id: 324, question: "Бинарный плюс (+) имеет приоритет выше, чем умножение (*)", correct: false, category: "js" },
  { id: 325, question: "Оператор присваивания (=) возвращает присвоенное значение", correct: true, category: "js" },
  { id: 326, question: "Можно использовать цепочку присваиваний: a = b = c = 5", correct: true, category: "js" },
  { id: 327, question: "Деление на ноль (1 / 0) в JS вызывает ошибку выполнения программы", correct: false, category: "js" },
  { id: 328, question: "Выражение 0 / 0 вернет NaN", correct: true, category: "js" },
  { id: 329, question: "Выражение NaN + 1 вернет NaN", correct: true, category: "js" },
  { id: 330, question: "В JS существует специальный оператор целочисленного деления //", correct: false, category: "js" },
  { id: 331, question: "Метод Math.floor() округляет число всегда в меньшую сторону", correct: true, category: "js" },
  { id: 332, question: "Метод Math.ceil() округляет число по математическим правилам", correct: false, category: "js" },
  { id: 333, question: "Метод Math.round() округляет до ближайшего целого", correct: true, category: "js" },
  { id: 334, question: "Оператор + работает быстрее, чем оператор -", correct: false, category: "js" },
  { id: 335, question: "Выражение '5' * '2' вернет 10", correct: true, category: "js" },
  { id: 336, question: "Выражение '5' / '2' вернет 2.5", correct: true, category: "js" },
  { id: 337, question: "Выражение 1 / -0 вернет -Infinity", correct: true, category: "js" },
  { id: 338, question: "Оператор **= возводит переменную в степень и присваивает результат", correct: true, category: "js" },
  { id: 339, question: "Выражение '5' + '2' вернет 7", correct: false, category: "js" },
  { id: 340, question: "Математические операторы всегда приводят свои операнды к числу (кроме бинарного плюса)", correct: true, category: "js" },
  { id: 341, question: "Оператор нестрогого равенства (==) приводит типы", correct: true, category: "js" },
  { id: 342, question: "Оператор строгого равенства (===) приводит типы", correct: false, category: "js" },
  { id: 343, question: "Строки сравниваются по их длине", correct: false, category: "js" },
  { id: 344, question: "Выражение 'a' > 'Z' вернет true (строчная буква больше заглавной)", correct: true, category: "js" },
  { id: 345, question: "Выражение null == undefined вернет true", correct: true, category: "js" },
  { id: 346, question: "Выражение null === undefined вернет true", correct: false, category: "js" },
  { id: 347, question: "При сравнении чисел и строк, JS преобразует строку в число (для <, >)", correct: true, category: "js" },
  { id: 348, question: "Выражение 0 == false вернет true", correct: true, category: "js" },
  { id: 349, question: "Выражение '' == false вернет true", correct: true, category: "js" },
  { id: 350, question: "Выражение 0 === false вернет true", correct: false, category: "js" },
  { id: 351, question: "Выражение NaN == NaN вернет true", correct: false, category: "js" },
  { id: 352, question: "Выражение NaN === NaN вернет true", correct: false, category: "js" },
  { id: 353, question: "Метод Object.is(NaN, NaN) вернет true", correct: true, category: "js" },
  { id: 354, question: "Выражение null > 0 вернет true", correct: false, category: "js" },
  { id: 355, question: "Выражение null >= 0 вернет true", correct: true, category: "js" },
  { id: 356, question: "Выражение undefined > 0 вернет true", correct: false, category: "js" },
  { id: 357, question: "Сравнение объектов через == проверяет их значения, а не ссылки", correct: false, category: "js" },
  { id: 358, question: "Сравнение двух пустых массивов ([] == []) вернет true", correct: false, category: "js" },
  { id: 359, question: "Выражение '2' > '12' вернет true", correct: true, category: "js" },
  { id: 360, question: "Оператор !== является противоположностью ===", correct: true, category: "js" },
  { id: 361, question: "Конструкция if (0) { ... } выполнится", correct: false, category: "js" },
  { id: 362, question: "Блок else всегда привязывается к первому if в цепочке", correct: false, category: "js" },
  { id: 363, question: "Тернарный оператор (?) всегда требует наличия ветки 'else' (:)", correct: true, category: "js" },
  { id: 364, question: "Можно использовать тернарный оператор без присваивания результата переменной", correct: true, category: "js" },
  { id: 365, question: "Тернарный оператор можно вкладывать друг в друга", correct: true, category: "js" },
  { id: 366, question: "В конструкции if можно объявить переменную с областью видимости только для if (например, if (let a = 1))", correct: false, category: "js" },
  { id: 367, question: "Пустая строка в if ('') будет приведена к true", correct: false, category: "js" },
  { id: 368, question: "Строка '0' в if ('0') будет приведена к true", correct: true, category: "js" },
  { id: 369, question: "Конструкция if...else if...else может содержать неограниченное число блоков else if", correct: true, category: "js" },
  { id: 370, question: "Если в блоке if только одна инструкция, фигурные скобки {} необязательны", correct: true, category: "js" },
  { id: 371, question: "Инструкция switch всегда работает быстрее, чем множественный if...else", correct: false, category: "js" },
  { id: 372, question: "В JS есть оператор if (!x) для проверки на ложность", correct: true, category: "js" },
  { id: 373, question: "Конструкция if (undefined) выполнит блок else", correct: true, category: "js" },
  { id: 374, question: "При использовании ? : оба выражения вычисляются всегда", correct: false, category: "js" },
  { id: 375, question: "Пустой массив [] в условии if даст false", correct: false, category: "js" },
  { id: 376, question: "Пустой объект {} в условии if даст true", correct: true, category: "js" },
  { id: 377, question: "Выражение if (null) выполнит блок кода", correct: false, category: "js" },
  { id: 378, question: "Тернарный оператор имеет более низкий приоритет, чем оператор присваивания", correct: false, category: "js" },
  { id: 379, question: "Значение выражения с тернарным оператором может быть функцией", correct: true, category: "js" },
  { id: 380, question: "Допускается использование break внутри обычного if (вне цикла или switch)", correct: false, category: "js" },
  { id: 381, question: "Логическое И (&&) возвращает последнее ложное значение", correct: false, category: "js" },
  { id: 382, question: "Логическое ИЛИ (||) возвращает первое ложное значение", correct: false, category: "js" },
  { id: 383, question: "Оператор НЕ (!) имеет самый высокий приоритет среди логических операторов", correct: true, category: "js" },
  { id: 384, question: "Оператор && имеет более высокий приоритет, чем ||", correct: true, category: "js" },
  { id: 385, question: "Выражение 1 || 0 && 2 вернет 2", correct: false, category: "js" },
  { id: 386, question: "Выражение 1 && 0 || 2 вернет 0", correct: false, category: "js" },
  { id: 387, question: "Выражение null || undefined || 0 вернет 0", correct: true, category: "js" },
  { id: 388, question: "Выражение 'text' && '' && 'str' вернет ''", correct: true, category: "js" },
  { id: 389, question: "Двойное НЕ (!!) преобразует значение в строку", correct: false, category: "js" },
  { id: 390, question: "Логическое И (&&) вычисляет операнды слева направо", correct: true, category: "js" },
  { id: 391, question: "Короткое замыкание в || означает, что правая часть не выполняется, если левая истинна", correct: true, category: "js" },
  { id: 392, question: "Операторы && и || могут возвращать не только логические значения", correct: true, category: "js" },
  { id: 393, question: "Выражение false || true вернет false", correct: false, category: "js" },
  { id: 394, question: "Выражение true && false вернет true", correct: false, category: "js" },
  { id: 395, question: "Логические операторы всегда возвращают true или false", correct: false, category: "js" },
  { id: 396, question: "Выражение !!NaN вернет false", correct: true, category: "js" },
  { id: 397, question: "Выражение !!undefined вернет true", correct: false, category: "js" },
  { id: 398, question: "Выражение !![] (пустой массив) вернет false", correct: false, category: "js" },
  { id: 399, question: "Оператор логическое ИЛИ (||) используется для присвоения значения по умолчанию", correct: true, category: "js" },
  { id: 400, question: "Результат выражения a && b && c будет c, если все переменные истинны", correct: true, category: "js" },
  { id: 401, question: "Оператор ?? возвращает левый операнд, если он равен null или undefined", correct: false, category: "js" },
  { id: 402, question: "Выражение 0 ?? 42 вернет 42", correct: false, category: "js" },
  { id: 403, question: "Выражение '' ?? 'default' вернет 'default'", correct: false, category: "js" },
  { id: 404, question: "Выражение false ?? true вернет true", correct: false, category: "js" },
  { id: 405, question: "Оператор ?? имеет более высокий приоритет, чем ||", correct: false, category: "js" },
  { id: 406, question: "Использование ?? вместе с && или || без скобок вызовет SyntaxError", correct: true, category: "js" },
  { id: 407, question: "Оператор ??= присваивает значение переменной, только если она равна null или undefined", correct: true, category: "js" },
  { id: 408, question: "Выражение let x = 0; x ??= 5; оставит x равным 0", correct: true, category: "js" },
  { id: 409, question: "Выражение let x = null; x ??= 5; изменит x на 5", correct: true, category: "js" },
  { id: 410, question: "Оператор ?? работает так же, как ||, для значения 0", correct: false, category: "js" },
  { id: 411, question: "Оператор ?? проверяет значение на истинность (truthy)", correct: false, category: "js" },
  { id: 412, question: "Оператор ??= является логическим оператором присваивания", correct: true, category: "js" },
  { id: 413, question: "Оператор ?? добавлен в стандарт ES2020", correct: true, category: "js" },
  { id: 414, question: "Выражение undefined ?? NaN вернет NaN", correct: true, category: "js" },
  { id: 415, question: "Выражение null ?? undefined вернет undefined", correct: true, category: "js" },
  { id: 416, question: "Цикл while проверяет условие после выполнения тела", correct: false, category: "js" },
  { id: 417, question: "Цикл do...while проверяет условие до выполнения тела", correct: false, category: "js" },
  { id: 418, question: "Цикл for имеет три части (инициализация, условие, шаг), и все они обязательны", correct: false, category: "js" },
  { id: 419, question: "Бесконечный цикл for записывается как for(;;)", correct: true, category: "js" },
  { id: 420, question: "Переменная, объявленная через let в инициализации for, доступна после завершения цикла", correct: false, category: "js" },
  { id: 421, question: "Инструкция break прерывает выполнение всего цикла", correct: true, category: "js" },
  { id: 422, question: "Инструкция continue переходит к следующей итерации цикла", correct: true, category: "js" },
  { id: 423, question: "Метки (labels) позволяют использовать break для выхода из вложенных циклов", correct: true, category: "js" },
  { id: 424, question: "Метки можно использовать с инструкцией if для перехода (goto)", correct: false, category: "js" },
  { id: 425, question: "В цикле for шаг выполняется до проверки условия", correct: false, category: "js" },
  { id: 426, question: "В JS существует цикл foreach, который является оператором языка (не методом)", correct: false, category: "js" },
  { id: 427, question: "Цикл for...in перебирает значения массива, а не индексы", correct: false, category: "js" },
  { id: 428, question: "Цикл for...of перебирает значения итерируемых объектов", correct: true, category: "js" },
  { id: 429, question: "Можно использовать break без метки внутри цикла while", correct: true, category: "js" },
  { id: 430, question: "В цикле while (true) {} браузер зависнет, если внутри нет break", correct: true, category: "js" },
  { id: 431, question: "Цикл do...while (false) не выполнится ни разу", correct: false, category: "js" },
  { id: 432, question: "В for...of можно перебирать свойства обычного объекта {}", correct: false, category: "js" },
  { id: 433, question: "Можно использовать const в цикле for...of", correct: true, category: "js" },
  { id: 434, question: "Можно использовать const в классическом цикле for (let i=0; ...)", correct: false, category: "js" },
  { id: 435, question: "Инструкция continue может принимать метку", correct: true, category: "js" },
  { id: 436, question: "Инструкция switch использует нестрогое сравнение (==)", correct: false, category: "js" },
  { id: 437, question: "Блок default обязателен в конструкции switch", correct: false, category: "js" },
  { id: 438, question: "Если в case нет инструкции break, выполнение перейдет к следующему case", correct: true, category: "js" },
  { id: 439, question: "В switch можно группировать несколько case для одного блока кода", correct: true, category: "js" },
  { id: 440, question: "Значением case может быть только число или строка", correct: false, category: "js" },
  { id: 441, question: "Значением case может быть выражение (например, case 1 + 2:)", correct: true, category: "js" },
  { id: 442, question: "Конструкция switch может быть заменена несколькими if...else if", correct: true, category: "js" },
  { id: 443, question: "Блок default всегда должен располагаться в конце switch", correct: false, category: "js" },
  { id: 444, question: "В switch проверка типов не происходит (как при ==)", correct: false, category: "js" },
  { id: 445, question: "Внутри switch можно объявлять переменные через let, видимые только в этом switch", correct: true, category: "js" },
  { id: 446, question: "В switch можно использовать return, если switch находится внутри функции", correct: true, category: "js" },
  { id: 447, question: "Каждый case создает свою собственную блочную область видимости по умолчанию", correct: false, category: "js" },
  { id: 448, question: "Ключевое слово break внутри switch прерывает работу всей функции", correct: false, category: "js" },
  { id: 449, question: "Один блок case может содержать несколько инструкций без фигурных скобок", correct: true, category: "js" },
  { id: 450, question: "Сравнение в switch работает аналогично методу Object.is()", correct: false, category: "js" },
  { id: 451, question: "Функция, не имеющая инструкции return, возвращает null", correct: false, category: "js" },
  { id: 452, question: "Функция в JS может быть вызвана с бОльшим числом аргументов, чем указано в параметрах", correct: true, category: "js" },
  { id: 453, question: "Лишние аргументы при вызове функции вызывают ошибку SyntaxError", correct: false, category: "js" },
  { id: 454, question: "Доступ ко всем переданным аргументам можно получить через псевдомассив 'arguments'", correct: true, category: "js" },
  { id: 455, question: "Параметры функции по умолчанию вычисляются в момент вызова", correct: true, category: "js" },
  { id: 456, question: "Функция не может возвращать другую функцию", correct: false, category: "js" },
  { id: 457, question: "Имя функции является обязательным для Function Declaration", correct: true, category: "js" },
  { id: 458, question: "Функции в JS являются объектами первого класса", correct: true, category: "js" },
  { id: 459, question: "Локальные переменные внутри функции перекрывают (затеняют) внешние с таким же именем", correct: true, category: "js" },
  { id: 460, question: "Аргументы в функцию передаются по ссылке, если это примитивные типы", correct: false, category: "js" },
  { id: 461, question: "Можно вызвать Function Declaration до того, как она объявлена в коде", correct: true, category: "js" },
  { id: 462, question: "Переменная arguments является настоящим массивом Array", correct: false, category: "js" },
  { id: 463, question: "Ключевое слово return можно использовать без значения", correct: true, category: "js" },
  { id: 464, question: "Можно ли объявить функцию внутри другой функции?", correct: true, category: "js" },
  { id: 465, question: "Параметры функции и переменные, объявленные внутри нее, видны снаружи", correct: false, category: "js" },
  { id: 466, question: "Function Expression создается только на верхнем уровне скрипта", correct: false, category: "js" },
  { id: 467, question: "Function Expression можно вызвать до ее определения в коде", correct: false, category: "js" },
  { id: 468, question: "Named Function Expression (NFE) позволяет функции ссылаться на саму себя внутри тела", correct: true, category: "js" },
  { id: 469, question: "Имя функции в Named Function Expression (NFE) доступно за пределами этой функции", correct: false, category: "js" },
  { id: 470, question: "Синтаксис Function Expression не требует указания имени функции", correct: true, category: "js" },
  { id: 471, question: "Function Expression подвержена 'всплытию' (hoisting) вместе с ее телом", correct: false, category: "js" },
  { id: 472, question: "Можно передать Function Expression в качестве аргумента в другую функцию", correct: true, category: "js" },
  { id: 473, question: "В конце Function Expression принято ставить точку с запятой", correct: true, category: "js" },
  { id: 474, question: "IIFE (Immediately Invoked Function Expression) выполняется сразу после создания", correct: true, category: "js" },
  { id: 475, question: "IIFE создается путем оборачивания функции в круглые скобки", correct: true, category: "js" },
  { id: 476, question: "Function Expression всегда анонимна", correct: false, category: "js" },
  { id: 477, question: "Переменная, которой присвоено Function Expression, хранит ссылку на саму функцию", correct: true, category: "js" },
  { id: 478, question: "typeof(Function Expression) возвращает 'object'", correct: false, category: "js" },
  { id: 479, question: "Коллбэк-функции (callbacks) часто передаются как Function Expression", correct: true, category: "js" },
  { id: 480, question: "NFE позволяет избежать проблем при вызове рекурсивной функции, если внешняя переменная изменилась", correct: true, category: "js" },
  { id: 481, question: "Стрелочные функции имеют свой собственный контекст 'this'", correct: false, category: "js" },
  { id: 482, question: "Стрелочные функции можно использовать в качестве конструкторов (с new)", correct: false, category: "js" },
  { id: 483, question: "В стрелочных функциях есть доступ к псевдомассиву 'arguments'", correct: false, category: "js" },
  { id: 484, question: "Стрелочные функции всегда анонимны", correct: true, category: "js" },
  { id: 485, question: "Если в стрелочной функции один параметр, круглые скобки вокруг него можно опустить", correct: true, category: "js" },
  { id: 486, question: "Если тело стрелочной функции состоит из одного выражения, фигурные скобки и return можно опустить", correct: true, category: "js" },
  { id: 487, question: "Стрелочные функции имеют свой объект 'super'", correct: false, category: "js" },
  { id: 488, question: "Стрелочные функции можно использовать как методы объектов, и их this будет указывать на этот объект", correct: false, category: "js" },
  { id: 489, question: "Метод bind() не может изменить 'this' стрелочной функции", correct: true, category: "js" },
  { id: 490, question: "Стрелочные функции были добавлены в стандарте ES6 (2015)", correct: true, category: "js" },
  { id: 491, question: "Стрелочная функция может быть передана как коллбэк (callback)", correct: true, category: "js" },
  { id: 492, question: "В стрелочной функции нельзя использовать параметры по умолчанию", correct: false, category: "js" },
  { id: 493, question: "При возврате объекта неявно, его нужно обернуть в круглые скобки: () => ({...})", correct: true, category: "js" },
  { id: 494, question: "Стрелочные функции поддерживают генераторы (yield)", correct: false, category: "js" },
  { id: 495, question: "Стрелочные функции автоматически привязываются к this во время их создания", correct: true, category: "js" },
  { id: 496, question: "JS — это однопоточный язык программирования", correct: true, category: "js" },
  { id: 497, question: "В JS существует сборщик мусора, который автоматически очищает память", correct: true, category: "js" },
  { id: 498, question: "Вызов функции setTimeout(func, 0) выполнит функцию немедленно, прервав текущий код", correct: false, category: "js" },
  { id: 499, question: "Глобальный объект в браузере называется 'document'", correct: false, category: "js" },
  { id: 500, question: "Переменные объявленные без let/const/var в нестрогом режиме становятся свойствами глобального объекта", correct: true, category: "js" }
];

export const comboRewards = {
  10: 1,
  20: 2,
  30: 4,
  40: 5,
  50: 6,
  60: 7,
  70: 8,
  80: 9,
  90: 10,
  100: 20,
};

export function getComboReward(combo) {
  if (combo % 10 !== 0) return 0;
  if (combo >= 100) return 20;
  if (combo >= 90) return 10;
  if (combo >= 80) return 9;
  if (combo >= 70) return 8;
  if (combo >= 60) return 7;
  if (combo >= 50) return 6;
  if (combo >= 40) return 5;
  if (combo >= 30) return 4;
  if (combo >= 20) return 2;
  if (combo >= 10) return 1;
  return 0;
}

export const TIMER_DURATION = 5000;
export const COMBO_SOUNDS = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];

export const CATEGORIES = {
  js: { name: "js", label: "JS" },
  all: { name: "all", label: "ALL" },
  basics: { name: "basics", label: "Основы" },
  strict: { name: "strict", label: "Strict" },
  types: { name: "types", label: "Типы" },
  variables: { name: "variables", label: "Переменные" },
  operators: { name: "operators", label: "Операторы" },
  control_flow: { name: "control-flow", label: "Управление" },
  functions: { name: "functions", label: "Функции" },
  objects: { name: "objects", label: "Объекты" },
  arrays: { name: "arrays", label: "Массивы" },
};